epochs: 15000
batch_size: 100
optimizer: adam
lr_rnn: 0.001
lr_readout: 0.001
lr_synthesiser: 0.00001
l2_norm: 0.0
rate_reg: 0.0
clip: 1.0
early_stopping: False
decay_lr: False
lr_scale: 0.1
lr_decay_patience: 10
reset_hidden: True
noisy: False
bptt: null
